#!/usr/bin/ruby -w
#
# Copyright 2011 Fredrik Wikstrom. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS'
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

stripsvn_version = '1.1'

dirname = nil
show_version = true
show_usage = false
if ARGV.length == 1
	dirname = ARGV.shift
else
	show_usage = true
end
if show_version
	puts "stripsvn v#{stripsvn_version} - Copyright (c) 2011 Fredrik Wikstrom"
end
if show_usage
	puts "Usage: stripsvn <directory>"
	exit
end

def deletedir(dirname)
	Dir.open(dirname) do |dir|
		dir.each do |name|
			if name == "." or name == ".."
				next
			end
			filename = File.join(dirname, name)
			if File.directory?(filename)
				deletedir(filename)
			else
				File.delete(filename)
			end
		end
	end
	Dir.delete(dirname)
end

def stripsvn(dirname)
	Dir.open(dirname) do |dir|
		dir.each do |name|
			if name == "." or name == ".."
				next
			end
			filename = File.join(dirname, name)
			if File.directory?(filename)
				if name == ".svn"
					deletedir(filename)
					puts "#{filename} deleted"
				else
					stripsvn(filename)
				end
			end
		end
	end
end

stripsvn(dirname)

