#!/usr/bin/ruby -w
#
# Copyright 2011 Fredrik Wikstrom. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS'
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

require 'getoptlong'

version_version = '1.1'

opts = GetoptLong.new(
	[ '--help', '-h', GetoptLong::NO_ARGUMENT ],
)

show_version = false
show_usage = false
if ARGV.length == 0
	show_version = true
	show_usage = true
end
opts.each do |opt, arg|
	case opt
		when '--help'
			show_version = true
			show_usage = true
	end
end
if ARGV.length > 0
	filename = ARGV.shift
end

if show_version
	puts "version v#{version_version} - Copyright (c) 2015 Fredrik Wikstrom"
end
if show_usage
	puts "Usage: version [OPTIONS] [FILENAME]"
	puts "Options:"
	puts "  -h, --help    Display this information"
	exit
end

ver = '$VER:'
i = 0
verstag = nil
File.open(filename, "rb") do |file|
	while ch = file.getc
		if ch != ver[i]
			i = 0
		end
		if ch == ver[i]
			i += 1
			if i == 5
				verstag = file.gets("(").chomp("(").strip
			end
		end
	end
end

if verstag
	puts verstag
end

